apiVersion: batch/v1
kind: CronJob
metadata:
  name: iam-eks-user-mapper
  namespace: kube-system
  labels:
    app: iam-eks-user-mapper
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 3
      activeDeadlineSeconds: 120
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          name: iam-eks-user-mapper
          labels:
            app: iam-eks-user-mapper
        spec:
          containers:
          - name: iam-eks-user-mapper
            image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/iam-eks-user-mapper:v0.0.1
            env:
              - name: AWS_DEFAULT_REGION
                value: "eu-central-1"
              - name: GROUPSANDROLES
                value: "Admin::system:masters"
          restartPolicy: Never
          serviceAccountName: iam-eks-user-mapper
          automountServiceAccountToken: true
