apiVersion: v1
kind: Pod
metadata:
  name: iam-eks-user-mapper
  namespace: kube-system
  labels:
    app: iam-eks-user-mapper
spec:
  serviceAccountName: iam-eks-user-mapper
  containers:
  - image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/iam-eks-user-mapper:v0.0.1
    imagePullPolicy: Always
    name: iam-eks-user-mapper
    env:
      - name: AWS_DEFAULT_REGION
        value: "eu-central-1"
      - name: GROUPSANDROLES
        value: "Admin::system:masters"
  restartPolicy: Never
  terminationGracePeriodSeconds: 3
