apiVersion: v1
kind: Pod
metadata:
  name: iam-eks-user-mapper
  namespace: kube-system
  labels:
    app: iam-eks-user-mapper
spec:
  serviceAccountName: iam-eks-user-mapper
  containers:
  - image: ghcr.io/tropnikovvl/eks-iam-mapper:master
    imagePullPolicy: Always
    name: iam-eks-user-mapper
    env:
      - name: AWS_DEFAULT_REGION
        value: "eu-central-1"
      - name: GROUPSANDROLES
        value: "Admin::system:masters,FoodGroup::food:food-developers,BackendGroup::backend:developers|backend:adminn|backend:adminn"
  restartPolicy: Never
  terminationGracePeriodSeconds: 3
